version: '3'

services:

#  db:
#    image: mysql:8.0.33-debian
#    environment:
#      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#    ports:
#      - "9906:3306"
#    volumes:
#      - db_data:/var/lib/mysql
#    networks:
#      - app-network

  app:
    container_name: php_web
    build:
      context: .
      dockerfile: Dockerfile
#    depends_on:
#      - db
    volumes:
      - ./src:/var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./src:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

#volumes:
#  db_data:
#    driver: local
